routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Input;

//Route::get('/', function () {
//    return view('welcome');
//});
Route::get('/', 'website\HomeController@index');
Route::get('/aboutus', 'website\HomeController@aboutus');
Route::resource('/services', 'website\ServicesController');
Route::resource('/ideas', 'website\IdeasController');
Route::resource('/news', 'website\NewsController');
Route::resource('/artists', 'website\ArtistController');
Route::resource('/contacts', 'website\ContactsController');
Route::get('/entertainment/{id}', 'website\ArtistController@entertainments');
Route::get('/entertainments/event_type/{id}', 'website\ArtistController@event_type');
Route::get('/entertainments/regional', 'website\ArtistController@entertainment_regional');
Route::get('/entertainments/global', 'website\ArtistController@entertainment_global');
Route::get('/entertainments/saudi', 'website\ArtistController@entertainment_saudi');
Route::resource('/events', 'website\EventsController');
Route::resource('/shows', 'website\ShowsController');
Route::resource('/reservations', 'website\ReservationsController');
Route::get('/reservation/{id}', 'website\ArtistController@create_reservation');
Route::post('/storereservation', 'website\ArtistController@store_reservation');
Route::get('/changeLang/{locale}', 'website\LocalizationController@index');
Route::get('/team', 'website\HomeController@team');




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/information/create/ajax-state', function () {
    $state_id = Input::get('state_id');
    $cities = \App\Models\City::where('country_id', '=', $state_id)->get();
    return json_encode($cities);

});
Route::get('/information/create/ajax-entertainment', function () {
    $entertainment_id = Input::get('entertainment_id');
    $subcategories = \App\Models\EntertainmentSubcategory::where('category_id', '=', $entertainment_id)->get();
    return json_encode($subcategories);


});
Route::get('/excelInsertMedicines', 'website\HomeController@add')->name('index');
Route::post('import', 'website\HomeController@import')->name('import');
Route::group(['prefix' => 'webadmin', 'middleware' => ['webadmin']], function () {

    Route::get('/dashboard', 'HomeController@index');

    Route::get('/logout', 'Auth\LoginController@logout');
    Route::resource('/events', 'admin\EventsController');
    Route::resource('/shows', 'admin\ShowsController');
    Route::resource('/artists', 'admin\ArtistsController');
    Route::resource('/reservations', 'admin\ReservationsController');
    Route::resource('/ideas', 'admin\IdeasController');
    Route::resource('/services', 'admin\ServicesController');
    Route::resource('/news', 'admin\NewsController');
    Route::resource('/currencies', 'admin\CurrenciesController');
    Route::resource('/countries', 'admin\CountriesController');
    Route::resource('/eventTypes', 'admin\EventTypesController');
    Route::resource('/cities', 'admin\CitiesController');
    Route::resource('/contacts', 'admin\ContactsController');
    Route::resource('/teams', 'admin\TeamsController');
    Route::resource('/sliders', 'admin\SlidersController');

    Route::resource('/settings', 'admin\SettingsController');
    Route::resource('/entertainments-types', 'admin\EntertainmentTypesController');
    Route::resource('/entertainments-subTypes', 'admin\EntertainmentSubTypesController');
    Route::get('/artist/pending', 'admin\ArtistsController@pendingArtists');
    Route::get('/artists/event-type/{id}', 'admin\ArtistsController@artistOfEventType');
    Route::get('/artist/accepted', 'admin\ArtistsController@acceptedArtists');
    Route::get('/artist/sendEmail', 'admin\ArtistsController@sendEmail');
    Route::post('/artist/storeEmail', 'admin\ArtistsController@storeEmail');
    Route::get('/artist/{id}/accept', 'admin\ArtistsController@accept');
    Route::get('/artist/{id}/reject', 'admin\ArtistsController@reject');
    Route::get('/contact/{id}/reply', 'admin\ContactsController@reply');
    Route::post('/contact/{id}/sendreply', 'admin\ContactsController@sendReply');
     Route::resource('/users', 'admin\UsersController');



});

app/Http/Controllers/admin/EventTypesController.php
<?php

namespace App\Http\Controllers\admin;

use App\Models\EventType;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class EventTypesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $eventTypes = EventType::all();
        return view('admin.eventTypes.index', compact('eventTypes'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.eventTypes.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,
            [
                'name_ar'=>'required',
//                'name_en'=>'required',
            ]);

        EventType::create([
            'name_ar' => $request->name_ar,
            'name_en' => $request->name_en,

        ]);

        return redirect('/webadmin/eventTypes')->withFlashMessage(json_encode(['success'=>true,'msg'=>'تم اضافة تصنيف العروض بنجاح']));



    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $eventType = EventType::find($id);
        return view('admin.eventTypes.edit', compact( 'eventType'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $eventType =EventType::find($id);
        $data=$request->all();
        $eventType->update($data);
        return redirect('/webadmin/eventTypes')->withFlashMessage(json_encode(['success'=>true,'msg'=>'تم تعديل تصنيف العروض بنجاح']));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        EventType::destroy($id);
        return back()->withFlashMessage(json_encode(['success'=>true,'msg'=>'تم الحذف بنجاح']));
    }
}

resources/views/admin/eventTypes/add.blade.php
@extends('admin.layouts.app')

@section('title')
    إضافة تصنيف عروض
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/eventTypes')}}" class="m-menu__link">
            <span class="m-menu__link-text"> تصنيفات العروض</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item" style="background: #e0deff;">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text">إضافة تصنيف عروض</span>
            <i class="m-menu__hor-arrow la la-angle-down"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')

    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                        إضافة تصنيف عروض
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form class="m-form m-form--fit m-form--label-align-right" action="/webadmin/eventTypes" method="post">
            {{ csrf_field() }}

            <div class="m-portlet__body">
                @include('admin.eventTypes.form')
            </div>
            <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                <div class="m-form__actions m-form__actions--solid">
                    <div class="row">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-6">
                            <button type="submit" class="btn btn-success">إضافة </button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection

resources/views/admin/eventTypes/artists.blade.php
@extends('admin.layouts.app')
@section('title')
    الفنانين
@endsection

@section('header')
    {!! Html::style('admin/vendors/custom/datatables/datatables.bundle.rtl.css') !!}
@endsection

@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسيه</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/artist/accepted')}}" class="m-menu__link">
            <span class="m-menu__link-text">الفنانين</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>


@endsection

@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        الفنانين
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <div>
                <a href="{{route('artists.create')}}" style="margin-bottom:20px" class="btn btn_primary btn btn-danger" ><i class=" fa fa-edit"></i>إضافة فنان</a>
            </div>


            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_testArea">
                <thead>
                <tr>
                    <th>#</th>
                    <th> اسم الفنان</th>
                    {{--<th> البريد الالكترونى</th>--}}
                    <th> دولة الاقامه</th>
                    <th>الجنسية</th>
                    <th>الحاله</th>
                    <th>الأدوات</th>
                </tr>
                </thead>
                <tbody>
                @foreach($artists as $index=> $artist)

                    <tr>
                        <td>{{++$index}}</td>
                        <td>{{$artist->name}} </td>
                        {{--                        <td>{{$artist->email}} </td>--}}
                        <td>{{$artist->city->country->name_ar}} </td>
                        <td>{{$artist->nationality}}</td>
                        <td>{{$artist->status}}</td>
                        <td>
                            <a  title="عرض"   href="/webadmin/artists/{{$artist->id}}" ><i class="fa fa-eye"></i></a>
                            <a  title="رفض"   href="/webadmin/artist/{{$artist->id}}/reject" ><i class="fa fa-ban"></i></a>

                            <a  title="تعديل" href="/webadmin/artists/{{$artist->id}}/edit" ><i class="fa fa-edit"></i></a>
                            <form class="inline-form-style"
                                  action="/webadmin/artists/{{ $artist->id }}"
                                  method="post">
                                <button type="submit" class="trash-btn">
                                    <span class="fa fa-trash"></span>
                                </button>
                                <input type="hidden" name="_method" value="delete" />
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            </form>

                        </td>
                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('footer')
    {{--{!! Html::script('admin/vendors/custom/datatables/datatables.bundle.js') !!}--}}
    {{--{!! Html::script('admin/custom/js/testArea/script.js') !!}--}}
@endsection

resources/views/admin/eventTypes/edit.blade.php
@extends('admin.layouts.app')

@section('title')
    تعديل تصنيف عروض
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/eventTypes')}}" class="m-menu__link">
            <span class="m-menu__link-text">تنصنيفات العروض </span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item" style="background: #e0deff;">
        <a href="javascript:;" class="m-menu__link">
            <span class="m-menu__link-text">تعديل تصنيف  </span>
            <i class="m-menu__hor-arrow la la-angle-down"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')

    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                        تعديل تصنيف
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        {!! Form::model($eventType,['route' => ['eventTypes.update' , $eventType->id],'method'=> 'PATCH','class'=>'m-form m-form--fit m-form--label-align-right']) !!}
        <div class="m-portlet__body">
            @include('admin.eventTypes.form')
        </div>
        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
            <div class="m-form__actions m-form__actions--solid">
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-6">
                        <button type="submit" class="btn btn-success">تعديل</button>
                    </div>
                </div>
            </div>
        </div>
    {!! Form::close() !!}
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection

resources/views/admin/eventTypes/form.blade.php
<div class="form-group m-form__group row">
    <label class="col-lg-1 col-form-label">اسم التصنيف بالعربيه: </label>
    <div class="col-lg-4{{ $errors->has('name_ar') ? ' has-danger' : '' }}">
        {!! Form::text('name_ar',null,['class'=>'form-control m-input','autofocus','placeholder'=>"اسم التصنيف بالعربيه"]) !!}
        @if ($errors->has('name_ar'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('name_ar') }}</strong>
            </span>
        @endif
    </div>
    <label class="col-lg-2 col-form-label">اسم التصنيف بالانجليزيه : </label>
    <div class="col-lg-5{{ $errors->has('name_en') ? ' has-danger' : '' }}">
        {!! Form::text('name_en',null,['class'=>'form-control m-input','placeholder'=>"اسم التصنيف بالانجليزيه"]) !!}
        @if ($errors->has('name_en'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('name_en') }}</strong>
            </span>
        @endif
    </div>
</div>

resources/views/admin/eventTypes/index.blade.php
@extends('admin.layouts.app')
@section('title')
تصنيفات العروض
@endsection

@section('header')
    {!! Html::style('admin/vendors/custom/datatables/datatables.bundle.rtl.css') !!}
@endsection

@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item active-top-bar">
        <a href="javascript:;" class="m-menu__link">
            <span class="m-menu__link-text">تصنيفات العروض</span>
            <i class="m-menu__hor-arrow la la-angle-down"></i>
        </a>
    </li>

@endsection

@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        تصنيفات العروض
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <div><a href="{{route('eventTypes.create')}}" style="margin-bottom:20px" class="btn btn_primary btn btn-danger" ><i class=" fa fa-edit"></i> إضافة تصنيف </a></div>


            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_country">
                <thead>
                <tr>
                    <th>#</th>
                    <th> الإسم باللغه العربيه</th>
                    <th> الإسم باللغه الانجليزيه</th>
                    <th>الأدوات</th>
                </tr>
                </thead>
                <tbody>
                @foreach($eventTypes as $index=>$eventType)
                    <tr>
                        <td>{{++$index}}</td>
                        <td>{{$eventType->name_ar}}</td>
                        <td>{{$eventType->name_en}}</td>
                        <td>
                            <a  title="تعديل" href="/webadmin/eventTypes/{{$eventType->id}}/edit" ><i class="fa fa-edit"></i></a>
                            <a  title="عرض الفنانين" href="/webadmin/artists/event-type/{{$eventType->id}}" ><i class="fa fa-eye"></i></a>
                            <form class="inline-form-style"
                                  action="/webadmin/eventTypes/{{ $eventType->id }}"
                                  method="post">
                                <button type="submit" class="trash-btn">
                                    <span class="fa fa-trash"></span>
                                </button>
                                <input type="hidden" name="_method" value="delete" />
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('footer')
    {{--{!! Html::script('admin/vendors/custom/datatables/datatables.bundle.js') !!}--}}
    {{--{!! Html::script('admin/custom/js/currencies.js') !!}--}}
@endsection