routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Input;

//Route::get('/', function () {
//    return view('welcome');
//});
Route::get('/', 'website\HomeController@index');
Route::get('/aboutus', 'website\HomeController@aboutus');
Route::resource('/services', 'website\ServicesController');
Route::resource('/ideas', 'website\IdeasController');
Route::resource('/news', 'website\NewsController');
Route::resource('/artists', 'website\ArtistController');
Route::resource('/contacts', 'website\ContactsController');
Route::get('/entertainment/{id}', 'website\ArtistController@entertainments');
Route::get('/entertainments/event_type/{id}', 'website\ArtistController@event_type');
Route::get('/entertainments/regional', 'website\ArtistController@entertainment_regional');
Route::get('/entertainments/global', 'website\ArtistController@entertainment_global');
Route::get('/entertainments/saudi', 'website\ArtistController@entertainment_saudi');
Route::resource('/events', 'website\EventsController');
Route::resource('/shows', 'website\ShowsController');
Route::resource('/reservations', 'website\ReservationsController');
Route::get('/reservation/{id}', 'website\ArtistController@create_reservation');
Route::post('/storereservation', 'website\ArtistController@store_reservation');
Route::get('/changeLang/{locale}', 'website\LocalizationController@index');
Route::get('/team', 'website\HomeController@team');




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/information/create/ajax-state', function () {
    $state_id = Input::get('state_id');
    $cities = \App\Models\City::where('country_id', '=', $state_id)->get();
    return json_encode($cities);

});
Route::get('/information/create/ajax-entertainment', function () {
    $entertainment_id = Input::get('entertainment_id');
    $subcategories = \App\Models\EntertainmentSubcategory::where('category_id', '=', $entertainment_id)->get();
    return json_encode($subcategories);


});
Route::get('/excelInsertMedicines', 'website\HomeController@add')->name('index');
Route::post('import', 'website\HomeController@import')->name('import');
Route::group(['prefix' => 'webadmin', 'middleware' => ['webadmin']], function () {

    Route::get('/dashboard', 'HomeController@index');

    Route::get('/logout', 'Auth\LoginController@logout');
    Route::resource('/events', 'admin\EventsController');
    Route::resource('/shows', 'admin\ShowsController');
    Route::resource('/artists', 'admin\ArtistsController');
    Route::resource('/reservations', 'admin\ReservationsController');
    Route::resource('/ideas', 'admin\IdeasController');
    Route::resource('/services', 'admin\ServicesController');
    Route::resource('/news', 'admin\NewsController');
    Route::resource('/currencies', 'admin\CurrenciesController');
    Route::resource('/countries', 'admin\CountriesController');
    Route::resource('/eventTypes', 'admin\EventTypesController');
    Route::resource('/cities', 'admin\CitiesController');
    Route::resource('/contacts', 'admin\ContactsController');
    Route::resource('/teams', 'admin\TeamsController');
    Route::resource('/sliders', 'admin\SlidersController');

    Route::resource('/settings', 'admin\SettingsController');
    Route::resource('/entertainments-types', 'admin\EntertainmentTypesController');
    Route::resource('/entertainments-subTypes', 'admin\EntertainmentSubTypesController');
    Route::get('/artist/pending', 'admin\ArtistsController@pendingArtists');
    Route::get('/artists/event-type/{id}', 'admin\ArtistsController@artistOfEventType');
    Route::get('/artist/accepted', 'admin\ArtistsController@acceptedArtists');
    Route::get('/artist/sendEmail', 'admin\ArtistsController@sendEmail');
    Route::post('/artist/storeEmail', 'admin\ArtistsController@storeEmail');
    Route::get('/artist/{id}/accept', 'admin\ArtistsController@accept');
    Route::get('/artist/{id}/reject', 'admin\ArtistsController@reject');
    Route::get('/contact/{id}/reply', 'admin\ContactsController@reply');
    Route::post('/contact/{id}/sendreply', 'admin\ContactsController@sendReply');
     Route::resource('/users', 'admin\UsersController');



});

app/Models/Show.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Show extends Model
{
    protected $table='shows';
    protected $guarded=[];
    public function images(){
        return $this->hasMany(ShowMedia::class,'show_id');
    }
    public function artist(){
        return $this->belongsTo(Artist::class,'artist_id');
    }
}

app/Http/Controllers/admin/ShowsController.php
<?php

namespace App\Http\Controllers\admin;

use App\Models\Artist;
use App\Models\Show;
use App\Models\ShowMedia;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ShowsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $shows=Show::all();
        return view('admin.shows.index',compact('shows'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $artists=Artist::where('status','accepted')->get();
        return view('admin.shows.add',compact('artists'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,
            [
                'title_ar'=>'required',
//                'title_en'=>'required',
//                'content_en'=>'required',
                'content_ar'=>'required',
                'date'=>'required',
                'artist_id'=>'required',
                'main_image'=>'required|file|mimes:jpeg,png,jpg,gif,mp4',
//                'medias.*'=>'sometimes|file|mimes:jpeg,png,jpg,gif,mp4'
            ]);

        $file = $request->file('main_image');

        $imageName = 'show-' . time() . '-' . uniqid() . '.' . $file->getClientOriginalExtension();
        $extension = $file->extension();
        $file->move(
            base_path() . '/public/uploads/shows/', $imageName
        );

        $show= Show::create([
            'main_image' => '/uploads/shows/' . $imageName,
            'title_ar' => $request->title_ar,
            'title_en' => $request->title_en,
            'content_en' => $request->content_en,
            'content_ar' => $request->content_ar,
            'date' => $request->date,
            'artist_id' => $request->artist_id,
        ]);
        // other photos and vedioes
        if ($request->hasFile('medias'))
        {
            $this->validate($request,
                [
                    'medias.*'=>'file|mimes:jpeg,png,jpg,gif,mp4'
                ]);
            $files=$request->file('medias');
            foreach ($files as $file)
            {
                $imageName = 'show-' . time() . '-' . uniqid() . '.' . $file->getClientOriginalExtension();
                $extension=$file->extension();
                $file->move(
                    base_path() . '/public/uploads/shows/', $imageName
                );

                ShowMedia::create([
                    'media' => '/uploads/shows/' . $imageName,
                    'type' =>$extension,
                    'show_id' => $show->id,
                ]);
            }

        }


        return redirect('/webadmin/shows')->withFlashMessage(json_encode(['success'=>true,'msg'=>'تم اضافة العرض بنجاح']));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $show=Show::find($id);
        return view('admin.shows.show',compact('show'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $show=Show::find($id);
        $artists=Artist::where('status','accepted')->get();

        return view('admin.shows.edit',compact('show','artists'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $show=Show::find($id);
        $data=$request->except(['main_image','medias']);
        $show->update($data);

        if ($request->hasFile('medias'))
        {
            $this->validate($request,
                [
                    'medias.*'=>'file|mimes:jpeg,png,jpg,gif,mp4'
                ]);
            //delete old medias
            ShowMedia::where('show_id',$id)->delete();
            $files=$request->file('medias');
            foreach ($files as $file)
            {
                $imageName = 'show-' . time() . '-' . uniqid() . '.' . $file->getClientOriginalExtension();
                $extension=$file->extension();
                $file->move(
                    base_path() . '/public/uploads/shows/', $imageName
                );

                ShowMedia::create([
                    'media' => '/uploads/shows/' . $imageName,
                    'type' =>$extension,
                    'show_id' => $show->id,
                ]);
            }

        }
        if ($request->hasFile('main_image'))
        {
            $this->validate($request,
                [
                    'main_image'=>'file|mimes:jpeg,png,jpg,gif,mp4'
                ]);
            $file=$request->file('main_image');

            $imageName = 'show-' . time() . '-' . uniqid() . '.' . $file->getClientOriginalExtension();
            $extension=$file->extension();
            $file->move(
                base_path() . '/public/uploads/shows/', $imageName
            );
            $show->update(['main_image'=>'/uploads/shows/'.$imageName]);

        }
        return redirect('/webadmin/shows')->withFlashMessage(json_encode(['success'=>true,'msg'=>'تم تعديل العرض بنجاح']));


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $show=Show::find($id);
        $medias= ShowMedia::where('show_id',$id)->get();
        foreach ($medias as $media) {
            $old_file =$media->media;
            if (is_file($old_file)) unlink($old_file);
            $media->delete();
        }
        if (is_file($show->main_image)) unlink($show->main_image);

        $show->delete();
        return redirect('/webadmin/shows')->withFlashMessage(json_encode(['success'=>true,'msg'=>'تم حذف العرض بنجاح']));
    }
}

app/Http/Controllers/website/ShowsController.php
<?php

namespace App\Http\Controllers\website;

use App\Models\Show;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ShowsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(app()->isLocale('ar')) {
            $shows=Show::where('title_ar','<>',null)->where('content_ar','<>',null)->with('images')->get();

        }else{
            $shows=Show::where('title_en','<>',null)->where('content_en','<>',null)->with('images')->get();

        }
        return view('website.shows',compact('shows'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $show=Show::find($id);
        $artist_id=$show->artist_id;
        if(app()->isLocale('ar')) {
            $related=Show::where('artist_id',$artist_id)->where('title_ar','<>',null)->where('content_ar','<>',null)->get();
        }else{
            $related=Show::where('artist_id',$artist_id)->where('title_en','<>',null)->where('content_en','<>',null)->get();

        }
        return view('website.show_details',compact('show','related'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/shows/add.blade.php
@extends('admin.layouts.app')

@section('title')
   إضافة عرض
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/shows')}}" class="m-menu__link">
            <span class="m-menu__link-text">الاكثر طلبا</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text">إضافة عرض</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
@endsection

@section('header')



@endsection

@section('content')
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                        إضافة عرض
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form class="m-form m-form--fit m-form--label-align-right" action="/webadmin/shows" method="post" enctype="multipart/form-data" >
            <div class="m-portlet__body">
                @csrf
                @include('admin.shows.form')
            </div>
            <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                <div class="m-form__actions m-form__actions--solid">
                    <div class="row">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-6">
                            <button type="submit" class="btn btn-success">إضافة</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')


@endsection

resources/views/admin/shows/edit.blade.php
@extends('admin.layouts.app')

@section('title')
    تعديل عرض
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/shows')}}" class="m-menu__link">
            <span class="m-menu__link-text">الاكثر طلبا</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text">تعديل عرض</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                        تعديل عرض
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        {!! Form::model($show,['route' => ['shows.update' , $show->id],'method'=> 'PATCH','class'=>'m-form m-form--fit m-form--label-align-right',"enctype"=>"multipart/form-data"]) !!}
        <div class="m-portlet__body">

            @include('admin.shows.form')
        </div>
        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
            <div class="m-form__actions m-form__actions--solid">
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-6">
                        <button type="submit" class="btn btn-success">تعديل</button>
                    </div>
                </div>
            </div>
        </div>
    {!! Form::close() !!}
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection

resources/views/admin/shows/form.blade.php
<div class="form-group m-form__group row">
    <label class="col-lg-2 col-form-label">الفنان : </label>
    <div class="col-lg-10{{ $errors->has('artist_id') ? ' has-danger' : '' }}">
        <select name="artist_id" data-placeholder="الفنان" class="form-control select-minimum">
            <option></option>
            <optgroup label="الفنان">
                @foreach($artists as $artist)
                    <option value="{{$artist->id}}" {{isset($show) && $show->artist_id==$artist->id ?'selected':''}}>{{$artist->name}} </option>
                @endforeach

            </optgroup>

        </select>
        @if ($errors->has('artist_id'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('artist_id') }}</strong>
            </span>
        @endif
    </div>

</div>
<div class="form-group m-form__group row">
    <label class="col-lg-2 col-form-label">عنوان العرض باللغة العربية: </label>
    <div class="col-lg-4{{ $errors->has('title_ar') ? ' has-danger' : '' }}">
        {!! Form::text('title_ar',old('title_ar'),['class'=>'form-control m-input','required','autofocus','placeholder'=> 'عنوان العرض باللغة العربية' ]) !!}
        @if ($errors->has('title_ar'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('title_ar') }}</strong>
            </span>
        @endif
    </div>
    <label class="col-lg-2 col-form-label">عنوان العرض باللغة الانجليزية : </label>
    <div class="col-lg-4{{ $errors->has('title_en') ? ' has-danger' : '' }}">
        {!! Form::text('title_en',old('title_en'),['class'=>'form-control m-input','placeholder'=>'عنوان العرض باللغة الانجليزية']) !!}
        @if ($errors->has('title_en'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('title_en') }}</strong>
            </span>
        @endif
    </div>
</div>
<div class="form-group m-form__group row">

    <label class="col-lg-2 col-form-label">وصف العرض باللغة العربية: </label>
    <div class="col-lg-10{{ $errors->has('content_ar') ? ' has-danger' : '' }}">
        <textarea name="content_ar" class="form-control summernote " required>{{isset($show) ? $show->content_ar :old('content_ar')}}</textarea>

        @if ($errors->has('content_ar'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('content_ar') }}</strong>
            </span>
        @endif
    </div>

</div>
<div class="form-group m-form__group row">

    <label class="col-lg-2 col-form-label">وصف العرض باللغة الانجليزية: </label>
    <div class="col-lg-10{{ $errors->has('content_en') ? ' has-danger' : '' }}">
        <textarea name="content_en" class="form-control summernote " >{{isset($show) ? $show->content_en :old('content_en')}}</textarea>

        @if ($errors->has('content_en'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('content_en') }}</strong>
            </span>
        @endif
    </div>

</div>
<div class="form-group m-form__group row">

    <label class="col-lg-2 col-form-label">تاريخ العرض: </label>
    <div class="col-lg-10{{ $errors->has('date') ? ' has-danger' : '' }}">

        <input type="text" name="date" value="{{isset($show) ?$show->date: old('date') }}" class="form-control ">
        @if ($errors->has('date'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('date') }}</strong>
            </span>
        @endif
    </div>

</div>
<div class="form-group m-form__group row">

    <label class="col-lg-2 col-form-label">الصورة الرئيسية: </label>
    <div class="col-lg-10{{ $errors->has('main_image') ? ' has-danger' : '' }}">

        <input type="file" name="main_image"  class="form-control uploadinput">
        @if ($errors->has('main_image'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('main_image') }}</strong>
            </span>
        @endif
    </div>

</div>

@if(isset($show) )
    <div class="col-12 text-center">
        <img src="{{$show->main_image}}" style="max-width:120px;max-height:120px align="center">

    </div>
@endif

<div class="form-group m-form__group row">
    <label class="col-lg-2 col-form-label">صور او فيديوهات أخرى: </label>
    <div class="col-lg-10{{ $errors->has('medias') ? ' has-danger' : '' }}">

        <input type="file" name="medias[]" multiple  class="form-control uploadinput">
        @if ($errors->has('medias'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('medias') }}</strong>
            </span>
        @endif
    </div>

</div>
{{--&& in_array($clinicsmodel->file_type,['jpeg','png','jpg','gif']--}}


@if(isset($show) && count($show->images)>0)
<div class='col-sm-8' style="text-align: center">
    @foreach($show->images as $item)
        @if(in_array($item->type,['jpeg','png','jpg','gif']))
            <img src="{{$item->media}}" style="max-width:120px;max-height:120px " align="center">

        @else
    <video width="120" height="120" controls>
        <source src="{{ $item->media }}" type="video/mp4" style="max-width:120px;max-height:120px ">
        Your browser does not support the video tag.
    </video>
        @endif
        @endforeach
</div>
@endif

resources/views/admin/shows/index.blade.php
@extends('admin.layouts.app')
@section('title')
    العروض
@endsection

@section('header')
    {!! Html::style('admin/vendors/custom/datatables/datatables.bundle.rtl.css') !!}
@endsection

@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسيه</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/shows')}}" class="m-menu__link">
            <span class="m-menu__link-text">الاكثر طلبا</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>


@endsection

@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        العروض
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <div><a href="{{route('shows.create')}}" style="margin-bottom:20px" class="btn btn_primary btn btn-danger" ><i class=" fa fa-edit"></i>إضافة عرض</a></div>


            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_testArea">
                <thead>
                <tr>
                    <th>#</th>
                    <th> عنوان العرض باللغة العربية</th>
                    <th> عنوان العرض باللغة الانجليزية</th>
                    <th>تاريخ العرض</th>
                    <th>الأدوات</th>
                </tr>
                </thead>
                <tbody>
                @foreach($shows as $index=> $show)

                    <tr>
                        <td>{{++$index}}</td>
                        <td>{{$show->title_ar}} </td>
                        <td>{{$show->title_en}} </td>
                        <td>{{$show->date}}</td>
                        <td>
                            <a  title="عرض"   href="/webadmin/shows/{{$show->id}}" ><i class="fa fa-eye"></i></a>
                            <a  title="تعديل" href="/webadmin/shows/{{$show->id}}/edit" ><i class="fa fa-edit"></i></a>
                            <form class="inline-form-style" 
                                  action="/webadmin/shows/{{ $show->id }}"
                                  method="post">
                                <button type="submit" class="trash-btn">
                                    <span class="fa fa-trash"></span>
                                </button>
                                <input type="hidden" name="_method" value="delete" />
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            </form>

                        </td>
                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('footer')
    {{--{!! Html::script('admin/vendors/custom/datatables/datatables.bundle.js') !!}--}}
    {{--{!! Html::script('admin/custom/js/testArea/script.js') !!}--}}
@endsection