routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Input;

//Route::get('/', function () {
//    return view('welcome');
//});
Route::get('/', 'website\HomeController@index');
Route::get('/aboutus', 'website\HomeController@aboutus');
Route::resource('/services', 'website\ServicesController');
Route::resource('/ideas', 'website\IdeasController');
Route::resource('/news', 'website\NewsController');
Route::resource('/artists', 'website\ArtistController');
Route::resource('/contacts', 'website\ContactsController');
Route::get('/entertainment/{id}', 'website\ArtistController@entertainments');
Route::get('/entertainments/event_type/{id}', 'website\ArtistController@event_type');
Route::get('/entertainments/regional', 'website\ArtistController@entertainment_regional');
Route::get('/entertainments/global', 'website\ArtistController@entertainment_global');
Route::get('/entertainments/saudi', 'website\ArtistController@entertainment_saudi');
Route::resource('/events', 'website\EventsController');
Route::resource('/shows', 'website\ShowsController');
Route::resource('/reservations', 'website\ReservationsController');
Route::get('/reservation/{id}', 'website\ArtistController@create_reservation');
Route::post('/storereservation', 'website\ArtistController@store_reservation');
Route::get('/changeLang/{locale}', 'website\LocalizationController@index');
Route::get('/team', 'website\HomeController@team');




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/information/create/ajax-state', function () {
    $state_id = Input::get('state_id');
    $cities = \App\Models\City::where('country_id', '=', $state_id)->get();
    return json_encode($cities);

});
Route::get('/information/create/ajax-entertainment', function () {
    $entertainment_id = Input::get('entertainment_id');
    $subcategories = \App\Models\EntertainmentSubcategory::where('category_id', '=', $entertainment_id)->get();
    return json_encode($subcategories);


});
Route::get('/excelInsertMedicines', 'website\HomeController@add')->name('index');
Route::post('import', 'website\HomeController@import')->name('import');
Route::group(['prefix' => 'webadmin', 'middleware' => ['webadmin']], function () {

    Route::get('/dashboard', 'HomeController@index');

    Route::get('/logout', 'Auth\LoginController@logout');
    Route::resource('/events', 'admin\EventsController');
    Route::resource('/shows', 'admin\ShowsController');
    Route::resource('/artists', 'admin\ArtistsController');
    Route::resource('/reservations', 'admin\ReservationsController');
    Route::resource('/ideas', 'admin\IdeasController');
    Route::resource('/services', 'admin\ServicesController');
    Route::resource('/news', 'admin\NewsController');
    Route::resource('/currencies', 'admin\CurrenciesController');
    Route::resource('/countries', 'admin\CountriesController');
    Route::resource('/eventTypes', 'admin\EventTypesController');
    Route::resource('/cities', 'admin\CitiesController');
    Route::resource('/contacts', 'admin\ContactsController');
    Route::resource('/teams', 'admin\TeamsController');
    Route::resource('/sliders', 'admin\SlidersController');

    Route::resource('/settings', 'admin\SettingsController');
    Route::resource('/entertainments-types', 'admin\EntertainmentTypesController');
    Route::resource('/entertainments-subTypes', 'admin\EntertainmentSubTypesController');
    Route::get('/artist/pending', 'admin\ArtistsController@pendingArtists');
    Route::get('/artists/event-type/{id}', 'admin\ArtistsController@artistOfEventType');
    Route::get('/artist/accepted', 'admin\ArtistsController@acceptedArtists');
    Route::get('/artist/sendEmail', 'admin\ArtistsController@sendEmail');
    Route::post('/artist/storeEmail', 'admin\ArtistsController@storeEmail');
    Route::get('/artist/{id}/accept', 'admin\ArtistsController@accept');
    Route::get('/artist/{id}/reject', 'admin\ArtistsController@reject');
    Route::get('/contact/{id}/reply', 'admin\ContactsController@reply');
    Route::post('/contact/{id}/sendreply', 'admin\ContactsController@sendReply');
     Route::resource('/users', 'admin\UsersController');



});

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    protected $table='contactus';
    protected $guarded=[];
}

app/Http/Controllers/admin/ContactsController.php
<?php

namespace App\Http\Controllers\admin;

use App\Models\Contact;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Mail;

class ContactsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contacts=Contact::all();
        return view('admin.contacts.index',compact('contacts'));
    }
    public function reply($id){
        $contact=Contact::find($id);
        return view('admin.contacts.reply',compact('contact'));

    }
    public function sendReply(Request $request,$id){
        $this->validate($request,
            [
                'message'=>'required',

            ]);
        $contact=Contact::find($id);
        $data = [
            'answer' => $request->message,

        ];


        Mail::send('emails.reply', $data, function ($message) use ($contact) {
            $message->from('smtp@monasabat.com', 'resetpassword@monasabat')
                ->to($contact->email)
                ->subject('Reply For Your Message, monasabat App');
        });
        return redirect('/webadmin/contacts')->withFlashMessage(json_encode(['success'=>true,'msg'=>'تم الرد بنجاح']));



    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $contact=Contact::find($id);
        return view('admin.contacts.show',compact('contact'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Contact::destroy($id);
        return back()->withFlashMessage(json_encode(['success'=>true,'msg'=>'تم الحذف بنجاح']));


    }
}

app/Http/Controllers/website/ContactsController.php
<?php

namespace App\Http\Controllers\website;

use App\Models\Contact;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ContactsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('website.contact');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'fullname' => 'required',
            'email' => 'required|email',
            'phone' => 'required',
            'message' => 'required',


        ]);
        $data=$request->all();
        Contact::create($data);
        return redirect()->back()->with('success',trans('site.contact_success'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/contacts/index.blade.php
@extends('admin.layouts.app')
@section('title')
    رسائل اتصل بنا
@endsection

@section('header')
    {!! Html::style('admin/vendors/custom/datatables/datatables.bundle.rtl.css') !!}
@endsection

@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسيه</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/contacts')}}" class="m-menu__link">
            <span class="m-menu__link-text">رسائل اتصل بنا </span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>


@endsection

@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        رسائل اتصل بنا
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            {{--<div><a href="{{route('events.create')}}" style="margin-bottom:20px" class="btn btn_primary btn btn-danger" ><i class=" fa fa-edit"></i>إضافة فاعلية</a></div>--}}


            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_testArea">
                <thead>
                <tr>
                    <th>#</th>
                    <th> الاسم بالكامل</th>
                    <th> البريد الالكترونى</th>
                    <th>رقم الهاتف</th>
                    <th>الأدوات</th>
                </tr>
                </thead>
                <tbody>
                @foreach($contacts as $index=> $contact)

                    <tr>
                        <td>{{++$index}}</td>
                        <td>{{$contact->fullname}} </td>
                        <td>{{$contact->email}} </td>
                        <td>{{$contact->phone}}</td>
                        <td>
                            <a  title="عرض"   href="/webadmin/contacts/{{$contact->id}}" ><i class="fa fa-eye"></i></a>
                            <a  title="الرد على الرسالة"   href="/webadmin/contact/{{$contact->id}}/reply" ><i class="fa fa-comment"></i></a>
                            {{--<a  title="تعديل" href="/webadmin/events/{{$event->id}}/edit" ><i class="fa fa-edit"></i></a>--}}
                            <form class="inline-form-style" 
                                  action="/webadmin/contacts/{{ $contact->id }}"
                                  method="post">
                                <button type="submit" class="trash-btn">
                                    <span class="fa fa-trash"></span>
                                </button>
                                <input type="hidden" name="_method" value="delete" />
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            </form>

                        </td>
                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('footer')
    {{--{!! Html::script('admin/vendors/custom/datatables/datatables.bundle.js') !!}--}}
    {{--{!! Html::script('admin/custom/js/testArea/script.js') !!}--}}
@endsection

resources/views/admin/contacts/reply.blade.php
@extends('admin.layouts.app')

@section('title')
    الرد على  الرسالة
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسة</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/contacts')}}" class="m-menu__link">
            <span class="m-menu__link-text">رسائل اتصل بنا</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text"> الرد على الرسالة </span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                        الرد على الرسالة
                    </h3>
                </div>
            </div>
            {{--<div style="margin-top:12px"><a href="/downloadFile/{{$patient->id}}" style="margin-bottom:20px" class="btn btn_primary btn btn-danger" ><i class=" fa fa-download"></i>{{trans('side.print_patient')}}</a></div>--}}
            {{--<div style="margin-top:12px"> <a href="#" title="{{trans('side.print')}}" class="greyscreen-print" onclick="window.print()"><i class="la la-print"></i></a>--}}
        </div>


        <div class="m-portlet__body">

            <!--begin::Form-->
            <form action="/webadmin/contact/{{$contact->id}}/sendreply" method="post">
                @csrf

            <div class="form-group m-form__group row">

                <label class="col-lg-2 col-form-label">الرد: </label>
                <div class="col-lg-10{{ $errors->has('message') ? ' has-danger' : '' }}">
                    <textarea name="message" class="form-control  " >{{old('message')}}</textarea>

                    @if ($errors->has('message'))
                        <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('message') }}</strong>
            </span>
                    @endif
                </div>

            </div>
                <div class="col-lg-6">
                    <button type="submit" class="btn btn-success">إرسال</button>
                </div>

            </form>

        </div>
    </div>


@endsection

resources/views/admin/contacts/show.blade.php
@extends('admin.layouts.app')

@section('title')
    عرض تفاصيل الرسالة
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسة</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/contacts')}}" class="m-menu__link">
            <span class="m-menu__link-text">رسائل اتصل بنا</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text">عرض تفاصيل الرسالة</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                        عرض تفاصيل الرسالة
                    </h3>
                </div>
            </div>
            {{--<div style="margin-top:12px"><a href="/downloadFile/{{$patient->id}}" style="margin-bottom:20px" class="btn btn_primary btn btn-danger" ><i class=" fa fa-download"></i>{{trans('side.print_patient')}}</a></div>--}}
            {{--<div style="margin-top:12px"> <a href="#" title="{{trans('side.print')}}" class="greyscreen-print" onclick="window.print()"><i class="la la-print"></i></a>--}}
            </div>


        <div class="m-portlet__body">

        <!--begin::Form-->
        {!! Form::model($contact,['route' => ['contacts.show' , $contact->id],'method'=> 'GET','class'=>'m-form m-form--fit m-form--label-align-right']) !!}
        {{--start patient data--}}
    <div class="form-group m-form__group row">
        <label class="col-lg-2 col-form-label">الاسم بالكامل: </label>
        <div class="col-lg-10{{ $errors->has('fullname') ? ' has-danger' : '' }}">
            {!! Form::text('fullname',old('fullname'),['class'=>'form-control m-input','disabled' ]) !!}
            @if ($errors->has('fullname'))
                <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('fullname') }}</strong>
            </span>
            @endif
        </div>

    </div>
    <div class="form-group m-form__group row">

        <label class="col-lg-2 col-form-label">البريد الالكترونى : </label>
        <div class="col-lg-10{{ $errors->has('email') ? ' has-danger' : '' }}">
            {!! Form::text('email',old('email'),['class'=>'form-control m-input','disabled']) !!}
            @if ($errors->has('email'))
                <span class="form-control-feedback" role="alert">
        <strong>{{ $errors->first('email') }}</strong>
        </span>
            @endif
        </div>

    </div>
    <div class="form-group m-form__group row">

        <label class="col-lg-2 col-form-label">رقم الهاتف : </label>
        <div class="col-lg-10{{ $errors->has('phone') ? ' has-danger' : '' }}">
            {!! Form::text('phone',old('phone'),['class'=>'form-control m-input','disabled']) !!}
            @if ($errors->has('phone'))
                <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('phone') }}</strong>
            </span>
            @endif
        </div>

    </div>
    <div class="form-group m-form__group row">

        <label class="col-lg-2 col-form-label">الرسالة: </label>
        <div class="col-lg-10{{ $errors->has('message') ? ' has-danger' : '' }}">
            <textarea name="message" class="form-control summernote " disabled="true">{{isset($contact) ? $contact->message :old('message')}}</textarea>

            @if ($errors->has('message'))
                <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('message') }}</strong>
            </span>
            @endif
        </div>

    </div>

    </div>
    </div>


@endsection